.TH target-isns 8
.SH NAME
.B target-isns
\- iSNS client for the Linux LIO iSCSI target
.SH SYNOPSIS
.B target-isns [OPTION]
.SH DESCRIPTION
.B target-isns
allows registering LIO iSCSI targets with an iSNS server.
.PP
The Internet Storage Name Service (iSNS, RFC 4171) protocol makes
easier to discover, manage and configure iSCSI devices.
.PP
With iSNS, iSCSI targets can be registered with a central iSNS server
and initiators can be configured to discover the targets by asking the
iSNS server.
.SH OPTIONS
.TP
.BR \-i ", " \-\-isns-server = HOSTNAME\fR
Set the hostname of the iSNS server.
.TP
.BR \-p ", " \-\-isns-port = \PORT\fR
Set the port of the iSNS server (default iSNS port is 3205).
.TP
.BR \-d ", " \-\-debug
Increase the debugging level (implies \-\-foreground).
.TP
.BR \-f ", " \-\-foreground
Run in the foreground.
.TP
.BR \-v ", " \-\-version
Print version information.
.TP
.BR \-h ", " \-\-help
Print a help message.
.SH FILES
.B /etc/target-isns.conf
is the default configuration file.
.PP
The following parameters can be set in the configuration file:
.TP
.BR isns_server = HOSTNAME\fR
Set the hostname of the iSNS server.
.TP
.BR isns_port = PORT
Set the port of the iSNS server (default iSNS port is 3205).
.TP
.BR log_level = [info|debug]
Set the log level (default is info).
.SH
BUGS
.PP
Please send bug reports to the upstream bug tracker at
\fBhttps://github.com/cvubrugier/target-isns/issues\fR.
.SH
SEE ALSO
.PP
\fBtargetcli\fR(8)
