.TH target-isns 8
.SH NAME
target-isns \- iSNS client for the Linux LIO iSCSI target
.SH SYNOPSIS
.B target-isns
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
target-isns allows registering LIO iSCSI targets with an iSNS server.
.PP
The Internet Storage Name Service (iSNS, RFC 4171) protocol makes
easier to discover, manage and configure iSCSI devices.
.PP
With iSNS, iSCSI targets can be registered with a central iSNS server
and initiators can be configured to discover the targets by asking the
iSNS server.
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-isns-server\fR=\fI\/HOSTNAME\/\fR
set the hostname of the iSNS server
.TP
\fB\-p\fR, \fB\-\-isns-port\fR=\fI\/PORT\/\fR
set the port number of the iSNS server (default iSNS port number is 3205)
.TP
\fB\-d\fR, \fB\-\-debug\fR
increase the debugging level (implies \fB\-\-foreground\fR)
.TP
\fB\-f\fR, \fB\-\-foreground\fR
run in the foreground
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
print this help message and exit
.SH FILES
\fB\//etc/target-isns.conf\fR
is the default configuration file.
.PP
The following parameters can be set in the configuration file:
.TP
\fB\/isns_server\fR=\fI\/HOSTNAME\fR
set the hostname of the iSNS server
.TP
\fB\/isns_port\fR=\fI\/PORT\fR
set the port number of the iSNS server (default iSNS port number is 3205)
.TP
\fB\/log_level\fR=[\fI\/info\fR\/|\fI\/debug\fR]
set the log level (default is info)
.SH
BUGS
.PP
Please send bug reports to the upstream bug tracker at
\fBhttps://github.com/open-iscsi/target-isns/issues\fR.
.SH
SEE ALSO
.PP
\fBtargetcli\fR(8)
